server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # BugRelay Backend Logs (Development)
  - job_name: bugrelay-backend-dev
    static_configs:
      - targets:
          - localhost
        labels:
          job: bugrelay-backend
          service: backend
          environment: development
          __path__: /var/log/bugrelay/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            request_id: request_id
            user_id: user_id
            method: method
            path: path
            status_code: status_code
            duration_ms: duration_ms
            context: context
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          service:
          method:
          status_code:
          environment:

  # Frontend Logs (Development)
  - job_name: bugrelay-frontend-dev
    static_configs:
      - targets:
          - localhost
        labels:
          job: bugrelay-frontend
          service: frontend
          environment: development
          __path__: /var/log/frontend/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            context: context
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          service:
          environment:

  # Docker Container Logs (Development)
  - job_name: docker-dev
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["com.docker.compose.project=bugrelay"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.+)'
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      - target_label: 'environment'
        replacement: 'development'
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: output

  # Audit Logs (Development)
  - job_name: audit-logs-dev
    static_configs:
      - targets:
          - localhost
        labels:
          job: audit-logs
          service: security
          environment: development
          __path__: /var/log/bugrelay/audit.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            audit: audit
            action: action
            resource: resource
            user_id: user_id
            security: security
            event: event
            severity: severity
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          action:
          resource:
          severity:
          event:
          environment: