global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    environment: 'production'
    cluster: 'bugrelay-prod'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 60s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # BugRelay Backend Application Metrics (Production)
  - job_name: 'bugrelay-backend-prod'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # BugRelay Frontend Application Metrics (Production)
  - job_name: 'bugrelay-frontend-prod'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 60s
    scrape_timeout: 10s

  # Nginx Metrics (if nginx-prometheus-exporter is added)
  - job_name: 'nginx-prod'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s

  # PostgreSQL Metrics (if postgres_exporter is added)
  - job_name: 'postgres-prod'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis Metrics (if redis_exporter is added)
  - job_name: 'redis-prod'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Loki Metrics
  - job_name: 'loki-prod'
    static_configs:
      - targets: ['loki:3100']
    scrape_interval: 60s

  # Grafana Metrics
  - job_name: 'grafana-prod'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 60s

  # AlertManager Metrics
  - job_name: 'alertmanager-prod'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 60s