global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'development'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # BugRelay Backend Application Metrics (Development)
  - job_name: 'bugrelay-backend-dev'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # BugRelay Frontend Application Metrics (Development)
  - job_name: 'bugrelay-frontend-dev'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL Database Metrics (if postgres_exporter is added)
  - job_name: 'postgres-dev'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Redis Metrics (if redis_exporter is added)
  - job_name: 'redis-dev'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Loki Metrics
  - job_name: 'loki-dev'
    static_configs:
      - targets: ['loki:3100']
    scrape_interval: 30s

  # Grafana Metrics
  - job_name: 'grafana-dev'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s